rdfpipe -i json-ld -o ttl ispy1-cedar.instance.0.json > ispy1-cedar.instance.0.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.1.json > ispy1-cedar.instance.1.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.10.json > ispy1-cedar.instance.10.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.100.json > ispy1-cedar.instance.100.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.101.json > ispy1-cedar.instance.101.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.102.json > ispy1-cedar.instance.102.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.103.json > ispy1-cedar.instance.103.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.104.json > ispy1-cedar.instance.104.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.105.json > ispy1-cedar.instance.105.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.106.json > ispy1-cedar.instance.106.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.107.json > ispy1-cedar.instance.107.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.108.json > ispy1-cedar.instance.108.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.109.json > ispy1-cedar.instance.109.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.11.json > ispy1-cedar.instance.11.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.110.json > ispy1-cedar.instance.110.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.111.json > ispy1-cedar.instance.111.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.112.json > ispy1-cedar.instance.112.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.113.json > ispy1-cedar.instance.113.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.114.json > ispy1-cedar.instance.114.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.115.json > ispy1-cedar.instance.115.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.116.json > ispy1-cedar.instance.116.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.117.json > ispy1-cedar.instance.117.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.118.json > ispy1-cedar.instance.118.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.119.json > ispy1-cedar.instance.119.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.12.json > ispy1-cedar.instance.12.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.120.json > ispy1-cedar.instance.120.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.121.json > ispy1-cedar.instance.121.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.122.json > ispy1-cedar.instance.122.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.123.json > ispy1-cedar.instance.123.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.124.json > ispy1-cedar.instance.124.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.125.json > ispy1-cedar.instance.125.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.126.json > ispy1-cedar.instance.126.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.127.json > ispy1-cedar.instance.127.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.128.json > ispy1-cedar.instance.128.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.129.json > ispy1-cedar.instance.129.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.13.json > ispy1-cedar.instance.13.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.130.json > ispy1-cedar.instance.130.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.131.json > ispy1-cedar.instance.131.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.132.json > ispy1-cedar.instance.132.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.133.json > ispy1-cedar.instance.133.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.134.json > ispy1-cedar.instance.134.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.135.json > ispy1-cedar.instance.135.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.136.json > ispy1-cedar.instance.136.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.137.json > ispy1-cedar.instance.137.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.138.json > ispy1-cedar.instance.138.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.139.json > ispy1-cedar.instance.139.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.14.json > ispy1-cedar.instance.14.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.140.json > ispy1-cedar.instance.140.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.141.json > ispy1-cedar.instance.141.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.142.json > ispy1-cedar.instance.142.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.143.json > ispy1-cedar.instance.143.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.144.json > ispy1-cedar.instance.144.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.145.json > ispy1-cedar.instance.145.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.146.json > ispy1-cedar.instance.146.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.147.json > ispy1-cedar.instance.147.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.148.json > ispy1-cedar.instance.148.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.149.json > ispy1-cedar.instance.149.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.15.json > ispy1-cedar.instance.15.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.150.json > ispy1-cedar.instance.150.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.151.json > ispy1-cedar.instance.151.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.152.json > ispy1-cedar.instance.152.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.153.json > ispy1-cedar.instance.153.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.154.json > ispy1-cedar.instance.154.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.155.json > ispy1-cedar.instance.155.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.156.json > ispy1-cedar.instance.156.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.157.json > ispy1-cedar.instance.157.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.158.json > ispy1-cedar.instance.158.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.159.json > ispy1-cedar.instance.159.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.16.json > ispy1-cedar.instance.16.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.160.json > ispy1-cedar.instance.160.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.161.json > ispy1-cedar.instance.161.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.162.json > ispy1-cedar.instance.162.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.163.json > ispy1-cedar.instance.163.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.164.json > ispy1-cedar.instance.164.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.165.json > ispy1-cedar.instance.165.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.166.json > ispy1-cedar.instance.166.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.167.json > ispy1-cedar.instance.167.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.168.json > ispy1-cedar.instance.168.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.169.json > ispy1-cedar.instance.169.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.17.json > ispy1-cedar.instance.17.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.170.json > ispy1-cedar.instance.170.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.171.json > ispy1-cedar.instance.171.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.172.json > ispy1-cedar.instance.172.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.173.json > ispy1-cedar.instance.173.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.174.json > ispy1-cedar.instance.174.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.175.json > ispy1-cedar.instance.175.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.176.json > ispy1-cedar.instance.176.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.177.json > ispy1-cedar.instance.177.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.178.json > ispy1-cedar.instance.178.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.179.json > ispy1-cedar.instance.179.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.18.json > ispy1-cedar.instance.18.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.180.json > ispy1-cedar.instance.180.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.181.json > ispy1-cedar.instance.181.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.182.json > ispy1-cedar.instance.182.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.183.json > ispy1-cedar.instance.183.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.184.json > ispy1-cedar.instance.184.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.185.json > ispy1-cedar.instance.185.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.186.json > ispy1-cedar.instance.186.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.187.json > ispy1-cedar.instance.187.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.188.json > ispy1-cedar.instance.188.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.189.json > ispy1-cedar.instance.189.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.19.json > ispy1-cedar.instance.19.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.190.json > ispy1-cedar.instance.190.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.191.json > ispy1-cedar.instance.191.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.192.json > ispy1-cedar.instance.192.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.193.json > ispy1-cedar.instance.193.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.194.json > ispy1-cedar.instance.194.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.195.json > ispy1-cedar.instance.195.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.196.json > ispy1-cedar.instance.196.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.197.json > ispy1-cedar.instance.197.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.198.json > ispy1-cedar.instance.198.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.199.json > ispy1-cedar.instance.199.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.2.json > ispy1-cedar.instance.2.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.20.json > ispy1-cedar.instance.20.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.200.json > ispy1-cedar.instance.200.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.201.json > ispy1-cedar.instance.201.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.202.json > ispy1-cedar.instance.202.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.203.json > ispy1-cedar.instance.203.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.204.json > ispy1-cedar.instance.204.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.205.json > ispy1-cedar.instance.205.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.206.json > ispy1-cedar.instance.206.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.207.json > ispy1-cedar.instance.207.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.208.json > ispy1-cedar.instance.208.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.209.json > ispy1-cedar.instance.209.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.21.json > ispy1-cedar.instance.21.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.210.json > ispy1-cedar.instance.210.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.211.json > ispy1-cedar.instance.211.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.212.json > ispy1-cedar.instance.212.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.213.json > ispy1-cedar.instance.213.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.214.json > ispy1-cedar.instance.214.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.215.json > ispy1-cedar.instance.215.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.216.json > ispy1-cedar.instance.216.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.217.json > ispy1-cedar.instance.217.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.218.json > ispy1-cedar.instance.218.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.219.json > ispy1-cedar.instance.219.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.22.json > ispy1-cedar.instance.22.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.220.json > ispy1-cedar.instance.220.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.23.json > ispy1-cedar.instance.23.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.24.json > ispy1-cedar.instance.24.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.25.json > ispy1-cedar.instance.25.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.26.json > ispy1-cedar.instance.26.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.27.json > ispy1-cedar.instance.27.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.28.json > ispy1-cedar.instance.28.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.29.json > ispy1-cedar.instance.29.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.3.json > ispy1-cedar.instance.3.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.30.json > ispy1-cedar.instance.30.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.31.json > ispy1-cedar.instance.31.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.32.json > ispy1-cedar.instance.32.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.33.json > ispy1-cedar.instance.33.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.34.json > ispy1-cedar.instance.34.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.35.json > ispy1-cedar.instance.35.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.36.json > ispy1-cedar.instance.36.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.37.json > ispy1-cedar.instance.37.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.38.json > ispy1-cedar.instance.38.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.39.json > ispy1-cedar.instance.39.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.4.json > ispy1-cedar.instance.4.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.40.json > ispy1-cedar.instance.40.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.41.json > ispy1-cedar.instance.41.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.42.json > ispy1-cedar.instance.42.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.43.json > ispy1-cedar.instance.43.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.44.json > ispy1-cedar.instance.44.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.45.json > ispy1-cedar.instance.45.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.46.json > ispy1-cedar.instance.46.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.47.json > ispy1-cedar.instance.47.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.48.json > ispy1-cedar.instance.48.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.49.json > ispy1-cedar.instance.49.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.5.json > ispy1-cedar.instance.5.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.50.json > ispy1-cedar.instance.50.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.51.json > ispy1-cedar.instance.51.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.52.json > ispy1-cedar.instance.52.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.53.json > ispy1-cedar.instance.53.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.54.json > ispy1-cedar.instance.54.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.55.json > ispy1-cedar.instance.55.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.56.json > ispy1-cedar.instance.56.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.57.json > ispy1-cedar.instance.57.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.58.json > ispy1-cedar.instance.58.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.59.json > ispy1-cedar.instance.59.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.6.json > ispy1-cedar.instance.6.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.60.json > ispy1-cedar.instance.60.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.61.json > ispy1-cedar.instance.61.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.62.json > ispy1-cedar.instance.62.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.63.json > ispy1-cedar.instance.63.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.64.json > ispy1-cedar.instance.64.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.65.json > ispy1-cedar.instance.65.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.66.json > ispy1-cedar.instance.66.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.67.json > ispy1-cedar.instance.67.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.68.json > ispy1-cedar.instance.68.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.69.json > ispy1-cedar.instance.69.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.7.json > ispy1-cedar.instance.7.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.70.json > ispy1-cedar.instance.70.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.71.json > ispy1-cedar.instance.71.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.72.json > ispy1-cedar.instance.72.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.73.json > ispy1-cedar.instance.73.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.74.json > ispy1-cedar.instance.74.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.75.json > ispy1-cedar.instance.75.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.76.json > ispy1-cedar.instance.76.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.77.json > ispy1-cedar.instance.77.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.78.json > ispy1-cedar.instance.78.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.79.json > ispy1-cedar.instance.79.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.8.json > ispy1-cedar.instance.8.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.80.json > ispy1-cedar.instance.80.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.81.json > ispy1-cedar.instance.81.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.82.json > ispy1-cedar.instance.82.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.83.json > ispy1-cedar.instance.83.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.84.json > ispy1-cedar.instance.84.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.85.json > ispy1-cedar.instance.85.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.86.json > ispy1-cedar.instance.86.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.87.json > ispy1-cedar.instance.87.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.88.json > ispy1-cedar.instance.88.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.89.json > ispy1-cedar.instance.89.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.9.json > ispy1-cedar.instance.9.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.90.json > ispy1-cedar.instance.90.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.91.json > ispy1-cedar.instance.91.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.92.json > ispy1-cedar.instance.92.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.93.json > ispy1-cedar.instance.93.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.94.json > ispy1-cedar.instance.94.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.95.json > ispy1-cedar.instance.95.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.96.json > ispy1-cedar.instance.96.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.97.json > ispy1-cedar.instance.97.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.98.json > ispy1-cedar.instance.98.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.instance.99.json > ispy1-cedar.instance.99.ttl
rdfpipe -i json-ld -o ttl ispy1-cedar.template.json > ispy1-cedar.template.ttl
