rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.43.jsonld > ./ISPY1-patient-clinical-subset.instance.43.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.20.jsonld > ./ISPY1-patient-clinical-subset.instance.20.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.204.jsonld > ./ISPY1-patient-clinical-subset.instance.204.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.208.jsonld > ./ISPY1-patient-clinical-subset.instance.208.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.51.jsonld > ./ISPY1-patient-clinical-subset.instance.51.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.32.jsonld > ./ISPY1-patient-clinical-subset.instance.32.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.216.jsonld > ./ISPY1-patient-clinical-subset.instance.216.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.67.jsonld > ./ISPY1-patient-clinical-subset.instance.67.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.189.jsonld > ./ISPY1-patient-clinical-subset.instance.189.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.220.jsonld > ./ISPY1-patient-clinical-subset.instance.220.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.79.jsonld > ./ISPY1-patient-clinical-subset.instance.79.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.197.jsonld > ./ISPY1-patient-clinical-subset.instance.197.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.75.jsonld > ./ISPY1-patient-clinical-subset.instance.75.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.2.jsonld > ./ISPY1-patient-clinical-subset.instance.2.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.16.jsonld > ./ISPY1-patient-clinical-subset.instance.16.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.185.jsonld > ./ISPY1-patient-clinical-subset.instance.185.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.152.jsonld > ./ISPY1-patient-clinical-subset.instance.152.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.131.jsonld > ./ISPY1-patient-clinical-subset.instance.131.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.140.jsonld > ./ISPY1-patient-clinical-subset.instance.140.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.123.jsonld > ./ISPY1-patient-clinical-subset.instance.123.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.98.jsonld > ./ISPY1-patient-clinical-subset.instance.98.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.176.jsonld > ./ISPY1-patient-clinical-subset.instance.176.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.86.jsonld > ./ISPY1-patient-clinical-subset.instance.86.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.168.jsonld > ./ISPY1-patient-clinical-subset.instance.168.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.115.jsonld > ./ISPY1-patient-clinical-subset.instance.115.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.164.jsonld > ./ISPY1-patient-clinical-subset.instance.164.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.119.jsonld > ./ISPY1-patient-clinical-subset.instance.119.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.94.jsonld > ./ISPY1-patient-clinical-subset.instance.94.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.107.jsonld > ./ISPY1-patient-clinical-subset.instance.107.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.121.jsonld > ./ISPY1-patient-clinical-subset.instance.121.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.142.jsonld > ./ISPY1-patient-clinical-subset.instance.142.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.133.jsonld > ./ISPY1-patient-clinical-subset.instance.133.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.150.jsonld > ./ISPY1-patient-clinical-subset.instance.150.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.96.jsonld > ./ISPY1-patient-clinical-subset.instance.96.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.178.jsonld > ./ISPY1-patient-clinical-subset.instance.178.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.105.jsonld > ./ISPY1-patient-clinical-subset.instance.105.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.88.jsonld > ./ISPY1-patient-clinical-subset.instance.88.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.166.jsonld > ./ISPY1-patient-clinical-subset.instance.166.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.84.jsonld > ./ISPY1-patient-clinical-subset.instance.84.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.117.jsonld > ./ISPY1-patient-clinical-subset.instance.117.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.174.jsonld > ./ISPY1-patient-clinical-subset.instance.174.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.109.jsonld > ./ISPY1-patient-clinical-subset.instance.109.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.30.jsonld > ./ISPY1-patient-clinical-subset.instance.30.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.214.jsonld > ./ISPY1-patient-clinical-subset.instance.214.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.53.jsonld > ./ISPY1-patient-clinical-subset.instance.53.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.22.jsonld > ./ISPY1-patient-clinical-subset.instance.22.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.206.jsonld > ./ISPY1-patient-clinical-subset.instance.206.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.41.jsonld > ./ISPY1-patient-clinical-subset.instance.41.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.218.jsonld > ./ISPY1-patient-clinical-subset.instance.218.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.14.jsonld > ./ISPY1-patient-clinical-subset.instance.14.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.69.jsonld > ./ISPY1-patient-clinical-subset.instance.69.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.187.jsonld > ./ISPY1-patient-clinical-subset.instance.187.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.77.jsonld > ./ISPY1-patient-clinical-subset.instance.77.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.199.jsonld > ./ISPY1-patient-clinical-subset.instance.199.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.0.jsonld > ./ISPY1-patient-clinical-subset.instance.0.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.195.jsonld > ./ISPY1-patient-clinical-subset.instance.195.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.18.jsonld > ./ISPY1-patient-clinical-subset.instance.18.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.65.jsonld > ./ISPY1-patient-clinical-subset.instance.65.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.113.jsonld > ./ISPY1-patient-clinical-subset.instance.113.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.80.jsonld > ./ISPY1-patient-clinical-subset.instance.80.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.170.jsonld > ./ISPY1-patient-clinical-subset.instance.170.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.101.jsonld > ./ISPY1-patient-clinical-subset.instance.101.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.92.jsonld > ./ISPY1-patient-clinical-subset.instance.92.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.162.jsonld > ./ISPY1-patient-clinical-subset.instance.162.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.137.jsonld > ./ISPY1-patient-clinical-subset.instance.137.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.129.jsonld > ./ISPY1-patient-clinical-subset.instance.129.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.154.jsonld > ./ISPY1-patient-clinical-subset.instance.154.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.125.jsonld > ./ISPY1-patient-clinical-subset.instance.125.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.158.jsonld > ./ISPY1-patient-clinical-subset.instance.158.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.146.jsonld > ./ISPY1-patient-clinical-subset.instance.146.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.8.jsonld > ./ISPY1-patient-clinical-subset.instance.8.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.191.jsonld > ./ISPY1-patient-clinical-subset.instance.191.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.61.jsonld > ./ISPY1-patient-clinical-subset.instance.61.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.183.jsonld > ./ISPY1-patient-clinical-subset.instance.183.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.10.jsonld > ./ISPY1-patient-clinical-subset.instance.10.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.73.jsonld > ./ISPY1-patient-clinical-subset.instance.73.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.4.jsonld > ./ISPY1-patient-clinical-subset.instance.4.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.202.jsonld > ./ISPY1-patient-clinical-subset.instance.202.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.26.jsonld > ./ISPY1-patient-clinical-subset.instance.26.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.45.jsonld > ./ISPY1-patient-clinical-subset.instance.45.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.38.jsonld > ./ISPY1-patient-clinical-subset.instance.38.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.210.jsonld > ./ISPY1-patient-clinical-subset.instance.210.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.49.jsonld > ./ISPY1-patient-clinical-subset.instance.49.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.34.jsonld > ./ISPY1-patient-clinical-subset.instance.34.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.57.jsonld > ./ISPY1-patient-clinical-subset.instance.57.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.71.jsonld > ./ISPY1-patient-clinical-subset.instance.71.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.6.jsonld > ./ISPY1-patient-clinical-subset.instance.6.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.181.jsonld > ./ISPY1-patient-clinical-subset.instance.181.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.12.jsonld > ./ISPY1-patient-clinical-subset.instance.12.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.63.jsonld > ./ISPY1-patient-clinical-subset.instance.63.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.193.jsonld > ./ISPY1-patient-clinical-subset.instance.193.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.55.jsonld > ./ISPY1-patient-clinical-subset.instance.55.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.28.jsonld > ./ISPY1-patient-clinical-subset.instance.28.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.212.jsonld > ./ISPY1-patient-clinical-subset.instance.212.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.36.jsonld > ./ISPY1-patient-clinical-subset.instance.36.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.47.jsonld > ./ISPY1-patient-clinical-subset.instance.47.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.59.jsonld > ./ISPY1-patient-clinical-subset.instance.59.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.200.jsonld > ./ISPY1-patient-clinical-subset.instance.200.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.24.jsonld > ./ISPY1-patient-clinical-subset.instance.24.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.160.jsonld > ./ISPY1-patient-clinical-subset.instance.160.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.103.jsonld > ./ISPY1-patient-clinical-subset.instance.103.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.90.jsonld > ./ISPY1-patient-clinical-subset.instance.90.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.172.jsonld > ./ISPY1-patient-clinical-subset.instance.172.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.111.jsonld > ./ISPY1-patient-clinical-subset.instance.111.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.82.jsonld > ./ISPY1-patient-clinical-subset.instance.82.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.139.jsonld > ./ISPY1-patient-clinical-subset.instance.139.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.144.jsonld > ./ISPY1-patient-clinical-subset.instance.144.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.127.jsonld > ./ISPY1-patient-clinical-subset.instance.127.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.156.jsonld > ./ISPY1-patient-clinical-subset.instance.156.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.135.jsonld > ./ISPY1-patient-clinical-subset.instance.135.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.148.jsonld > ./ISPY1-patient-clinical-subset.instance.148.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.114.jsonld > ./ISPY1-patient-clinical-subset.instance.114.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.87.jsonld > ./ISPY1-patient-clinical-subset.instance.87.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.169.jsonld > ./ISPY1-patient-clinical-subset.instance.169.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.99.jsonld > ./ISPY1-patient-clinical-subset.instance.99.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.177.jsonld > ./ISPY1-patient-clinical-subset.instance.177.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.106.jsonld > ./ISPY1-patient-clinical-subset.instance.106.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.95.jsonld > ./ISPY1-patient-clinical-subset.instance.95.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.118.jsonld > ./ISPY1-patient-clinical-subset.instance.118.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.165.jsonld > ./ISPY1-patient-clinical-subset.instance.165.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.130.jsonld > ./ISPY1-patient-clinical-subset.instance.130.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.153.jsonld > ./ISPY1-patient-clinical-subset.instance.153.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.122.jsonld > ./ISPY1-patient-clinical-subset.instance.122.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.141.jsonld > ./ISPY1-patient-clinical-subset.instance.141.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.78.jsonld > ./ISPY1-patient-clinical-subset.instance.78.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.196.jsonld > ./ISPY1-patient-clinical-subset.instance.196.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.66.jsonld > ./ISPY1-patient-clinical-subset.instance.66.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.188.jsonld > ./ISPY1-patient-clinical-subset.instance.188.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.184.jsonld > ./ISPY1-patient-clinical-subset.instance.184.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.17.jsonld > ./ISPY1-patient-clinical-subset.instance.17.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.3.jsonld > ./ISPY1-patient-clinical-subset.instance.3.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.74.jsonld > ./ISPY1-patient-clinical-subset.instance.74.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.205.jsonld > ./ISPY1-patient-clinical-subset.instance.205.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.21.jsonld > ./ISPY1-patient-clinical-subset.instance.21.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.42.jsonld > ./ISPY1-patient-clinical-subset.instance.42.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.217.jsonld > ./ISPY1-patient-clinical-subset.instance.217.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.33.jsonld > ./ISPY1-patient-clinical-subset.instance.33.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.50.jsonld > ./ISPY1-patient-clinical-subset.instance.50.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.209.jsonld > ./ISPY1-patient-clinical-subset.instance.209.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.1.jsonld > ./ISPY1-patient-clinical-subset.instance.1.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.76.jsonld > ./ISPY1-patient-clinical-subset.instance.76.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.198.jsonld > ./ISPY1-patient-clinical-subset.instance.198.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.68.jsonld > ./ISPY1-patient-clinical-subset.instance.68.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.186.jsonld > ./ISPY1-patient-clinical-subset.instance.186.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.15.jsonld > ./ISPY1-patient-clinical-subset.instance.15.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.64.jsonld > ./ISPY1-patient-clinical-subset.instance.64.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.19.jsonld > ./ISPY1-patient-clinical-subset.instance.19.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.194.jsonld > ./ISPY1-patient-clinical-subset.instance.194.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.52.jsonld > ./ISPY1-patient-clinical-subset.instance.52.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.215.jsonld > ./ISPY1-patient-clinical-subset.instance.215.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.31.jsonld > ./ISPY1-patient-clinical-subset.instance.31.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.219.jsonld > ./ISPY1-patient-clinical-subset.instance.219.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.40.jsonld > ./ISPY1-patient-clinical-subset.instance.40.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.207.jsonld > ./ISPY1-patient-clinical-subset.instance.207.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.23.jsonld > ./ISPY1-patient-clinical-subset.instance.23.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.89.jsonld > ./ISPY1-patient-clinical-subset.instance.89.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.167.jsonld > ./ISPY1-patient-clinical-subset.instance.167.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.104.jsonld > ./ISPY1-patient-clinical-subset.instance.104.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.97.jsonld > ./ISPY1-patient-clinical-subset.instance.97.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.179.jsonld > ./ISPY1-patient-clinical-subset.instance.179.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.108.jsonld > ./ISPY1-patient-clinical-subset.instance.108.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.175.jsonld > ./ISPY1-patient-clinical-subset.instance.175.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.116.jsonld > ./ISPY1-patient-clinical-subset.instance.116.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.85.jsonld > ./ISPY1-patient-clinical-subset.instance.85.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.143.jsonld > ./ISPY1-patient-clinical-subset.instance.143.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.120.jsonld > ./ISPY1-patient-clinical-subset.instance.120.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.151.jsonld > ./ISPY1-patient-clinical-subset.instance.151.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.132.jsonld > ./ISPY1-patient-clinical-subset.instance.132.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.39.jsonld > ./ISPY1-patient-clinical-subset.instance.39.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.44.jsonld > ./ISPY1-patient-clinical-subset.instance.44.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.27.jsonld > ./ISPY1-patient-clinical-subset.instance.27.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.203.jsonld > ./ISPY1-patient-clinical-subset.instance.203.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.56.jsonld > ./ISPY1-patient-clinical-subset.instance.56.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.35.jsonld > ./ISPY1-patient-clinical-subset.instance.35.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.48.jsonld > ./ISPY1-patient-clinical-subset.instance.48.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.211.jsonld > ./ISPY1-patient-clinical-subset.instance.211.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.60.jsonld > ./ISPY1-patient-clinical-subset.instance.60.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.190.jsonld > ./ISPY1-patient-clinical-subset.instance.190.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.9.jsonld > ./ISPY1-patient-clinical-subset.instance.9.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.5.jsonld > ./ISPY1-patient-clinical-subset.instance.5.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.72.jsonld > ./ISPY1-patient-clinical-subset.instance.72.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.11.jsonld > ./ISPY1-patient-clinical-subset.instance.11.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.182.jsonld > ./ISPY1-patient-clinical-subset.instance.182.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.155.jsonld > ./ISPY1-patient-clinical-subset.instance.155.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.128.jsonld > ./ISPY1-patient-clinical-subset.instance.128.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.136.jsonld > ./ISPY1-patient-clinical-subset.instance.136.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.147.jsonld > ./ISPY1-patient-clinical-subset.instance.147.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.159.jsonld > ./ISPY1-patient-clinical-subset.instance.159.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.124.jsonld > ./ISPY1-patient-clinical-subset.instance.124.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.171.jsonld > ./ISPY1-patient-clinical-subset.instance.171.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.81.jsonld > ./ISPY1-patient-clinical-subset.instance.81.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.112.jsonld > ./ISPY1-patient-clinical-subset.instance.112.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.163.jsonld > ./ISPY1-patient-clinical-subset.instance.163.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.93.jsonld > ./ISPY1-patient-clinical-subset.instance.93.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.100.jsonld > ./ISPY1-patient-clinical-subset.instance.100.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.126.jsonld > ./ISPY1-patient-clinical-subset.instance.126.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.145.jsonld > ./ISPY1-patient-clinical-subset.instance.145.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.138.jsonld > ./ISPY1-patient-clinical-subset.instance.138.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.149.jsonld > ./ISPY1-patient-clinical-subset.instance.149.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.134.jsonld > ./ISPY1-patient-clinical-subset.instance.134.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.157.jsonld > ./ISPY1-patient-clinical-subset.instance.157.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.91.jsonld > ./ISPY1-patient-clinical-subset.instance.91.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.102.jsonld > ./ISPY1-patient-clinical-subset.instance.102.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.161.jsonld > ./ISPY1-patient-clinical-subset.instance.161.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.83.jsonld > ./ISPY1-patient-clinical-subset.instance.83.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.110.jsonld > ./ISPY1-patient-clinical-subset.instance.110.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.173.jsonld > ./ISPY1-patient-clinical-subset.instance.173.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.37.jsonld > ./ISPY1-patient-clinical-subset.instance.37.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.213.jsonld > ./ISPY1-patient-clinical-subset.instance.213.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.29.jsonld > ./ISPY1-patient-clinical-subset.instance.29.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.54.jsonld > ./ISPY1-patient-clinical-subset.instance.54.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.25.jsonld > ./ISPY1-patient-clinical-subset.instance.25.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.201.jsonld > ./ISPY1-patient-clinical-subset.instance.201.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.58.jsonld > ./ISPY1-patient-clinical-subset.instance.58.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.46.jsonld > ./ISPY1-patient-clinical-subset.instance.46.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.13.jsonld > ./ISPY1-patient-clinical-subset.instance.13.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.180.jsonld > ./ISPY1-patient-clinical-subset.instance.180.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.7.jsonld > ./ISPY1-patient-clinical-subset.instance.7.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.70.jsonld > ./ISPY1-patient-clinical-subset.instance.70.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.192.jsonld > ./ISPY1-patient-clinical-subset.instance.192.ttl
rdfpipe -i json-ld -o ttl ./ISPY1-patient-clinical-subset.instance.62.jsonld > ./ISPY1-patient-clinical-subset.instance.62.ttl
